### ISSUE TITLE
MEFE API - Edit a user

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/lambda2sns#12]
This describes the MEFE API to edit a Unee-T user.
See https://github.com/unee-t/frontend/pull/735 for more details.

# The Payload needed by the MEFE API:

```
{
	"actionType": "EDIT_USER",
	"requestorUserId": "2HPpT3FYjQ2PacskN",
	"userId": "chFmfTz34ahKcSNM9",
	"emailAddress": "nao+91210@example.com",
	"firstName": "Naor",
	"lastName": "Biton",
	"phoneNumber": "80000000",
	"creatorId": "2HPpT3FYjQ2PacskN",
	"bzfeEmailAddress": "nao+91210@example.com"
}
```

Example response:
```
{
    "timestamp": "2019-03-22T11:21:41.663Z"
}
```

# The Payload generated by the SQL via Lambda:

```
{
	"updateUserRequestId": 1,
	"actionType": "EDIT_USER",
	"requestorUserId": "2HPpT3FYjQ2PacskN",
	"userId": "chFmfTz34ahKcSNM9",
	"emailAddress": "nao+91210@example.com",
	"firstName": "Naor",
	"lastName": "Biton",
	"phoneNumber": "80000000",
	"creatorId": "2HPpT3FYjQ2PacskN",
	"bzfeEmailAddress": "nao+91210@example.com"
}
```

# The SQL to run after the API returns a success:

```
SET @update_user_request_id = `updateUserRequestId` ;
SET @updated_datetime = `timestamp` ;  [(the SQL formatted timestamp of the reply from the MEFE API)]
CALL `ut_update_success_mefe_user`;
```

@kaihendry Let me know when all is ready on your side (Golang) so I can test end to end.

**Comment by kaihendry** [comment]
Quickly implemented it, but I get `/aws/lambda/alambda_simple {"fields":{},"level":"info","timestamp":"2019-03-26T05:26:05.186608865Z","message":"Response code 400, Body: \"No user found for requestorUserId 2HPpT3FYjQ2PacskN; No user found for user to edit userId chFmfTz34ahKcSNM9; No user found for proposed creatorId 2HPpT3FYjQ2PacskN\""}
` from MEFE

**Comment by franck-boullier** [comment]
OK this might be normal...
I'll try to do the end to end test now with newly created users...

**Comment by franck-boullier** [comment]
# The Test:

- In the Unee-T enterprise database, change the name of a person - PASSED (MEFE user id = `tp6uQiYQPyDLFQvF3`)
- Check that the name is updated in the Mongo collection `user` - PASSED
- Check that the Unee-T enterprise database table is updated with the timestamp of the update - FAILED

The payload was 
```
{"userId": "tp6uQiYQPyDLFQvF3", "lastName": "Derp", "creatorId": "YYeAutqzDY3MeqbNC", "firstName": "Derpette", "actionType": "EDIT_USER", "phoneNumber": null, "emailAddress": "xxxx@gmail.com", "requestorUserId": "YYeAutqzDY3MeqbNC", "bzfeEmailAddress": "xxxx@gmail.com", "updateUserRequestId": 4}
```

# Other Issues:

- The AWS notification seems to be sent twice for some reason...

**Comment by franck-boullier** [comment]
# Fixed issues:

> The AWS notification seems to be sent twice for some reason...

This is now fixed (I updated the lambda triggers...)

# Pending issue:

- Check that the Unee-T enterprise database table is updated with the timestamp of the update - FAILED

@kaihendry any idea?

**Comment by kaihendry** [comment]
Please try again

**Comment by franck-boullier** [comment]
# The Test:

- In the Unee-T enterprise database, change the name of a person - PASSED (MEFE user id = `tp6uQiYQPyDLFQvF3`)
- Check that the name is updated in the Mongo collection `user` - PASSED
- Check that the Unee-T enterprise database table is updated with the timestamp of the update - PASSED

Thanks @kaihendry!

**Comment by franck-boullier** [comment]
I'm closing this as this works.

@nbiton what happens if the email is updated to an email that is already associate to an existing Unee-T user?
The BZ side will not allow 2 different BZFE account with the same email address...

I'll open a different issue to discuss what will be the best strategy to handle that.
