### ISSUE TITLE
case_new_message

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/lambda2sns#5]
We have a SNS event active each time a case is updated.
The notification type is `case_new_message`

We need to generate the email notification for this type of notification too.

**Comment by kaihendry** [comment]
https://github.com/unee-t/lambda2sns/blob/master/tests/events/case_new_message.json

**Comment by kaihendry** [comment]
Who do emails needs to be sent to here?

https://github.com/unee-t/lambda2sns/blob/master/tests/events/case_new_message.json#L12-L13

* new_case_assignee_user_id
* current_list_of_invitees

Anyone else?

**Comment by kaihendry** [comment]
Bit confused as to where *assignee_user_id* disappeared to. https://github.com/unee-t/lambda2sns/pull/2

Do you see (my confusion in) how assignee_user_id is somehow **old_case_assignee_user_id** or **new_case_assignee_user_id** ?

Why has this changed and [broken the existing notification code](https://github.com/unee-t/frontend/blob/master/imports/api/rest/post-process-db-change-message.js#L38)?

Can you be explicit to who are recipients are in this case please. Pull out the values from https://github.com/unee-t/lambda2sns/blob/master/tests/events/case_new_message.json

**Comment by franck-boullier** [comment]
Notifications should be sent to:
- The reporter: `case_reporter_user_id` 
and
- The current assignee: `new_case_assignee_user_id`
and
- All the invited user: `current_list_of_invitees`
and
- exclude the user who has initiated the modification: `created_by_user_id`

The notification routine must check if each user has subscribed to this type of notifications before sending the email notification.

**Comment by franck-boullier** [comment]
Above comment updated for better clarity

**Comment by franck-boullier** [comment]
@kaihendry please note that the names of the variable for the user who has initiated the change (`user_id`) for the notification type `case_updated` is NOT the same as the variable for the user who has created a new message (`created_by_user_id`) for the notification type `case_new_message`.

**Comment by kaihendry** [comment]
IIUC https://github.com/unee-t/lambda2sns/blob/master/tests/events/case_new.json has been replaced with case_new_message. So I will be deleting case_new. Very confusing.

**Comment by kaihendry** [comment]
@franck-boullier for clarity please list the user ids who will receive the message.
