### ISSUE TITLE
case_assignee_updated clarify who should recieve message

### ISSUE THREAD

**Issue by kaihendry** [unee-t/lambda2sns#8]
https://github.com/unee-t/lambda2sns/blob/master/tests/events/case_assignee_updated.json

Does the **assignee_user_id** get ignored in favour of **new_case_assignee_user_id**?

**Comment by franck-boullier** [comment]
> Does the assignee_user_id get ignored in favour of new_case_assignee_user_id?

`assignee_user_id`:
- Should be ignored in the notification type `case_assignee_updated` (I will remove this from the payload in the future).
- Does not exist in any other type of notification as it has been replaced by
  - `old_case_assignee_user_id`
  and 
  - `new_case_assignee_user_id`

**Comment by kaihendry** [comment]
Ok, this is the way it works now https://github.com/unee-t/frontend/blob/master/imports/api/rest/post-process-db-change-message.js#L58
